/** Conocimiento técnico destilado de la "Biblia del Conocimiento Meraldi"
 * (16 módulos, compilada 2026-07-02). Guía curada y bilingüe de nivel 1 para que el
 * redactor eduque al comprador y responda con precisión, en español o en inglés.
 * Hechos declarativos, NO narrativa de venta. Prioriza temas frecuentes del comprador:
 * las 6 variables Meraldi, precio, tratamiento, jardín, orígenes, certificación y
 * valorización honesta. */
export const GUIA_HECHOS = `LAS 6 VARIABLES MERALDI
Una esmeralda se entiende por seis variables: peso, color, claridad, corte, origen y tratamiento. Las primeras cuatro son el estándar internacional (4C: color, claridad, corte, peso); Méraldi añade origen y tratamiento porque en esmeralda ambos mueven el precio tanto como el color. Frase de marca: "la belleza emociona; la información construye confianza."
EN: An emerald is understood through six variables: weight, color, clarity, cut, origin, and treatment. The first four are the international 4C standard; Meraldi adds origin and treatment because in emerald both move the price as much as color does.

PESO (QUILATES)
El quilate (ct) es la unidad de peso de las gemas: 1 ct = 0,2 gramos = 100 puntos. No mide tamaño visual: dos piedras del mismo peso pueden verse distintas según la talla, las proporciones y la densidad del material. El precio por quilate no sube de forma lineal con el tamaño: a calidad comparable, cruzar los umbrales de 1, 3, 5 y 10 quilates multiplica el valor por quilate, así que una piedra grande no siempre vale proporcionalmente más que una pequeña de mejor calidad. El peso sin calidad no vale: existen piedras pequeñas de gran color que cuestan por quilate mucho más que piedras grandes de calidad mediocre.
EN: A carat (ct) is the gemstone weight unit: 1 ct = 0.2 grams = 100 points. It does not measure visual size. Price per carat rises in steps, not linearly, as size crosses thresholds (1, 3, 5, 10 ct) at comparable quality — so a bigger stone is not automatically worth more per carat than a smaller, finer one.

COLOR
La esmeralda es la variedad verde a verde azulada del berilo, coloreada por cromo y/o vanadio (el hierro modula el tono hacia el azul y suprime la fluorescencia). El color es el factor más determinante del valor — se estima que puede representar más de la mitad del valor en piedras finas. Se evalúa en tres dimensiones: tono (hue: lo más buscado es verde puro a ligeramente azulado, sin matiz amarillento en gamas altas), saturación (la variable decisiva: "vívida" es la palabra premium, gris o marrón la castiga) y tono de claridad tonal (ni tan claro que parezca berilo verde común, ni tan oscuro que pierda vida; el rango medio a medio-oscuro es la franja fina). También importa la distribución: color parejo cara arriba vale más que color con zonas irregulares.
EN: Emerald is the green to bluish-green variety of beryl, colored by chromium and/or vanadium (iron shifts the tone toward blue and suppresses fluorescence). Color is the single most decisive value factor, judged on hue (pure green to slightly bluish is most sought), saturation (vivid is the premium word; gray or brown undertones hurt value) and tone (medium to medium-dark is the fine range).

CLARIDAD Y JARDÍN (INCLUSIONES)
Las inclusiones naturales de una esmeralda se llaman, en conjunto, "jardín". La esmeralda es una gema clasificada como Tipo III por el GIA: se espera que tenga inclusiones visibles a simple vista, así que su estándar de claridad NO es el del diamante. Una esmeralda "eye-clean" (sin inclusiones visibles a unos 15 cm) es una rareza que multiplica el precio; una esmeralda natural absolutamente limpia a lupa es tan atípica que despierta sospecha de sintética. El jardín no es un defecto en sí mismo: se evalúa si compromete o no la transparencia, el brillo y la durabilidad de la piedra (fisuras que llegan a la superficie sí son un riesgo real, y son la puerta del tratamiento). Tipos de inclusión típicos: trifásicas (líquido + gas + cristal, clásicas en Colombia pero ya no prueba exclusiva de origen colombiano desde 2014), bifásicas, cristales de pirita, calcita, mica, y fracturas naturales.
EN: An emerald's natural inclusions are collectively called its "jardin" (garden). Emerald is GIA Type III — visible inclusions are expected and normal, so its clarity standard is not the diamond standard. A truly "eye-clean" emerald is a rare, price-multiplying exception. Inclusions are not automatically a flaw; what matters is whether they compromise transparency, brightness, and durability. Surface-reaching fractures are the real durability risk and the entry point for treatment.

CORTE
El corte aporta proporciones, simetría, brillo y protección de las zonas más frágiles de la piedra. La talla llamada "corte esmeralda" (rectangular o cuadrada, de esquinas cortadas y facetas escalonadas) nació específicamente para esta gema: protege las esquinas del golpe y luce el color. Un corte deficiente puede generar "ventana" (zona central donde se ve a través de la piedra, perdiendo color y valor) o "extinción" (zonas oscuras por exceso de profundidad). Una piedra bien tallada, aunque conserve menos peso, suele valer más por quilate que una piedra pesada mal proporcionada.
EN: Cut provides proportion, symmetry, brilliance, and protection for the stone's most fragile zones. The classic "emerald cut" (rectangular, step-faceted, cut corners) was designed specifically to protect this gem's corners while showing off its color. Poor cutting causes a "window" (a see-through central zone that loses color and value) or "extinction" (dark zones from excess depth).

ORIGEN — COLOMBIA
Colombia es el referente histórico de mayor prestigio del mundo esmeraldero, con una geología única: sus esmeraldas nacen de salmueras hidrotermales que circularon por lutitas negras sedimentarias del Cretácico, sin ningún volcán ni granito involucrado — un modelo geológico prácticamente exclusivo a escala comercial. Esa química (alto cromo, muy bajo hierro) produce el verde cálido y vivo característico de las colombianas finas. El origen aporta contexto y reputación, pero no determina el valor por sí solo: conviene documentarlo con opinión de laboratorio cuando la pieza lo amerita, y nunca prometer una mina específica sin trazabilidad real, porque la mayoría de certificados dicen solo "Colombia" como país, no la mina exacta.
EN: Colombia is the historic, most prestigious source in the emerald world, with a uniquely non-volcanic hydrothermal geology (hot brines through Cretaceous black shales) that yields warm, low-iron, vivid green stones. Origin adds context and reputation but does not determine value alone — most lab certificates state the country ("Colombia"), not the specific mine, so a specific mine should never be promised without real traceability.

LAS MINAS COLOMBIANAS
Colombia tiene dos cinturones esmeraldíferos en la Cordillera Oriental. El cinturón occidental agrupa Muzo-Quípama, Coscuez, La Pita/Maripí, Peñas Blancas y Yacopí-La Palma. El cinturón oriental agrupa Chivor, Gachalá, Macanal y Somondoco.
Muzo es el nombre más prestigioso del mundo esmeraldero, sinónimo histórico del "verde Muzo": profundo y cálido, con bajo hierro y alto cromo. Fue explotada por el pueblo muzo antes de la conquista española y hoy su operación histórica la lleva Muzo Emerald Colombia.
Chivor es la mina de los muiscas (Somondoco), la primera en manos españolas (1537-1545); su verde tiende a un componente ligeramente más azulado o frío que Muzo, con piedras de gran limpieza. De Chivor salió el famoso cristal Esmeralda Patricia (632 ct).
Coscuez es una de las tres grandes minas históricas, con más de 400 años de producción; desde 2018 es operada por Fura Gems con un plan de inversión de cerca de US$200 millones.
La Pita (distrito de Maripí, Boyacá) protagonizó buena parte de la producción colombiana fina de los años 2000 y 2010; su calidad es comparable a la de Muzo — la distinción entre minas del cinturón occidental es de matiz, no de categoría.
Gachalá, en el cinturón oriental, dio nombre a la Esmeralda Gachalá (858 ct, hallada en 1967, hoy en el Smithsonian).
Regla de honestidad: la mejor mina es la que produjo la mejor piedra que el cliente tiene delante; nunca se denigra un origen frente a otro, y las diferencias de color entre minas son tendencias de mercado, no leyes.
EN: Colombia has two emerald belts. Western belt: Muzo-Quípama, Coscuez, La Pita/Maripí, Peñas Blancas, Yacopí-La Palma. Eastern belt: Chivor, Gachalá, Macanal, Somondoco. Muzo is the most prestigious name in the emerald world ("Muzo green": deep, warm, low iron). Chivor, the Muisca mine, tends toward a slightly cooler, bluer green with very clean stones. Coscuez, one of the three great historic mines, has been operated by Fura Gems since 2018. La Pita produced much of Colombia's fine output in the 2000s-2010s, comparable in quality to Muzo. Gachalá gave its name to the 858-ct Gachalá Emerald (Smithsonian). No mine is denigrated versus another — quality is judged stone by stone.

COMPARACIÓN CON ZAMBIA Y BRASIL (Y OTROS ORÍGENES)
Zambia (mina Kagem, en Kafubu) es hoy la mayor mina de esmeraldas del mundo por volumen y organiza subastas que marcan precios del segmento; su geología (esquistos + pegmatita) produce esmeraldas con más hierro, de tono más frío o azulado. Brasil es probablemente el mayor productor en volumen, con calidad muy variable y precios en general más accesibles; su mina emblema es Belmont (Itabira, Minas Gerais). Otros orígenes relevantes: Afganistán (Panjshir, material fino comparable al colombiano en su mejor gama), Pakistán (Swat), Etiopía (Shakiso, entrada reciente desde 2016), Zimbabwe (Sandawana, histórica) y Rusia (Malysheva).
Posición honesta de Méraldi: Zambia y Brasil producen esmeraldas espléndidas, y existen piezas zambianas o brasileñas mejores que muchas colombianas mediocres — la calidad se juzga pieza a pieza, nunca por bandera. La colombiana fina cuesta más por una combinación real: prestigio histórico, química de bajo hierro que da un verde más cálido, rareza de un modelo geológico único y demanda sostenida en el segmento alto. Nunca se afirma que "las zambianas son malas" ni que "las etíopes no valen": son estéticas y mercados distintos, y Méraldi se especializa en colombiana porque es su origen y su trazabilidad.
EN: Zambia's Kagem mine is today the world's largest emerald mine by volume; its schist-and-pegmatite geology yields higher-iron, cooler/bluer stones, and its auctions set benchmark prices for that segment. Brazil is likely the largest producer by volume, with widely variable quality and generally more accessible prices (flagship mine: Belmont). Other relevant origins: Afghanistan (Panjshir), Pakistan (Swat), Ethiopia (Shakiso, since 2016), Zimbabwe (Sandawana), Russia (Malysheva). Meraldi's honest position: fine Zambian or Brazilian stones can outshine mediocre Colombian ones — quality is judged stone by stone, never by flag. Colombian fine emerald commands a premium from real factors: historical prestige, a low-iron warm green, geological rarity, and sustained high-end demand.

TRATAMIENTO / ACEITE / RESINA
La gran mayoría de las esmeraldas del comercio están tratadas: sus fisuras naturales que llegan a la superficie se rellenan con aceite (tradicionalmente aceite de cedro) o con resinas más modernas (tipo Opticon u otras) para mejorar la apariencia de claridad. Es una práctica antigua, universal y perfectamente aceptada siempre que se declare. La filosofía de la casa: "lo importante no es negar los tratamientos, sino declararlos con precisión."
Los laboratorios usan una escala de grado de relleno: sin tratamiento / sin indicios ("none"), insignificante, menor ("minor"), moderado ("moderate") y significativo ("significant"). El grado mide la cantidad de relleno presente, no la "cantidad de belleza añadida", y puede cambiar con el tiempo si el relleno se degrada o si la piedra se re-aceita — el certificado describe el estado a su fecha de emisión. A igualdad de color y talla, el precio escala fuertemente al bajar el grado de tratamiento: una piedra fina sin tratamiento y con certificado puede valer varias veces su gemela con tratamiento "minor". "Minor" es, de hecho, el estándar honesto y esperado del comercio fino de esmeraldas declarado — lo preocupante no es que una piedra tenga "minor", sino que no se informe nada.
Lo que NO existe (o es prácticamente inaceptable) en esmeralda comercial: tratamiento por calor (a diferencia del rubí o zafiro, el calor daña la esmeralda), irradiación, o el teñido — el tinte sin declarar es una bandera roja de fraude.
EN: The vast majority of commercial emeralds are treated: surface-reaching natural fissures are filled with oil (traditionally cedar oil) or modern resin to improve apparent clarity — an old, universal, fully accepted practice as long as it is disclosed. Labs grade the amount of filler on a scale: none, insignificant, minor, moderate, significant. "Minor" is the honest, expected standard for fine emerald trade when disclosed — the real concern is a stone with undisclosed treatment, not the word "minor" itself. Heat treatment, irradiation, and undisclosed dyeing are not accepted practices for emerald.

CUIDADO DE LA PIEDRA
Regla de oro: nunca limpieza con ultrasonido ni vapor, y evitar solventes, ácidos o calor de soplete (el joyero debe proteger o desmontar la piedra al soldar), porque pueden extraer o dañar el relleno de fisuras. La limpieza segura es con agua tibia, jabón neutro y un paño suave. El re-aceitado periódico (cada cierto número de años) es mantenimiento normal y legítimo, comparable a pulir un mueble fino — no es un defecto ni un engaño, siempre que se informe. Aunque la esmeralda tiene una dureza alta (7,5-8 en la escala de Mohs, por encima del cuarzo del polvo ambiental), su tenacidad frente a golpes es más baja cuando la piedra viene fisurada (lo habitual), así que se recomienda un engaste protector (bisel o halo) y sentido común: quitarse el anillo para deporte, jardinería o playa.
EN: Golden rule: never clean with ultrasonic or steam devices, and avoid solvents, acids, or torch heat (a jeweler must protect or remove the stone before soldering), since these can strip or damage fissure fillers. Safe cleaning is warm water, mild soap, and a soft cloth. Periodic re-oiling is normal, legitimate maintenance. Although emerald is hard (7.5-8 Mohs), its toughness is lower when naturally fissured, so a protective setting (bezel or halo) and common sense (removing the ring for sports, gardening, or the beach) are recommended.

PRECIO Y CÓMO SE EXPLICA
La pregunta correcta no es solo "¿cuánto vale por quilate?", sino qué calidad, tratamiento, origen, rareza y confianza se está comprando. El precio total de una piedra suelta se calcula como precio por quilate multiplicado por el peso en quilates (por ejemplo, 3.000 USD/ct por 4 ct son 12.000 USD) — este cálculo de la piedra sí se puede dar con exactitud. El precio de una joya terminada (piedra montada en metal, con manufactura y diseño) depende además del oro u otros metales, la manufactura y el diseño, y esa parte la afina un asesor humano de Méraldi — no se inventa ni se estima de forma genérica. No existe una "lista oficial" de precio por quilate: los rangos van desde decenas de dólares por quilate en calidad comercial hasta cifras de seis dígitos en piezas récord; se dan siempre como rangos orientativos por franja de calidad, confirmados con piezas reales.
EN: The right question isn't just "how much per carat" but what quality, treatment, origin, rarity, and trust you're buying. A loose stone's total price is price-per-carat times carat weight (e.g., 3,000 USD/ct × 4 ct = 12,000 USD) — this stone-only calculation can be given exactly. A finished jewelry piece's price also depends on metal, manufacturing, and design, and that part is refined by a human Meraldi advisor — it is never invented or generically estimated.

CERTIFICACIÓN: LOCAL Y GIA/INTERNACIONAL
Un certificado o reporte gemológico documenta, a la fecha de emisión, la identidad de la piedra (natural o sintética, especie y variedad), su peso y medidas, el tratamiento detectado y su grado, y — en laboratorios de color de primer nivel — una opinión de origen geográfico. Un certificado NO es una tasación de precio ni una garantía de belleza, y no es un documento eterno: el grado de tratamiento puede cambiar si la piedra se re-aceita.
Laboratorios internacionales de primer nivel: GIA (el más reconocido globalmente), SSEF y Gübelin Gem Lab (los referentes suizos de alta gama y subastas), AGL, y otros como Guild o GRS. Laboratorios nacionales colombianos: CDTEC, el laboratorio de Rodrigo Giraldo, el Instituto Gemológico Colombiano, entre otros del entorno bogotano. En Méraldi, toda venta se acompaña por defecto de un certificado nacional; la certificación GIA está disponible a pedido del cliente, implica enviar la piedra a Estados Unidos y tiene un costo adicional que se cotiza aparte. Para reventa internacional o piezas de inversión pesan más los laboratorios internacionales (GIA/SSEF/Gübelin/AGL); para el mercado nacional y piezas comerciales, el laboratorio colombiano es el estándar aceptado y económico — no es que unos laboratorios "mientan" y otros no, es una cuestión de reconocimiento de marca y alcance instrumental. La opinión de origen de un laboratorio es eso, una opinión informada, no un acta notarial: dos laboratorios serios pueden discrepar en piedras límite.
EN: A gem report documents, as of its issue date, the stone's identity (natural or synthetic, species/variety), weight and measurements, detected treatment and its grade, and — from top color labs — an opinion on geographic origin. It is NOT a price appraisal, a beauty guarantee, or a permanent document (treatment grade can change after re-oiling). Top international labs: GIA, SSEF, Gübelin Gem Lab, AGL. Colombian national labs: CDTEC and peers. Meraldi includes a national certificate by default with every sale; GIA certification is available on request, requires shipping the stone to the US, and is quoted as an additional service.

SINTÉTICAS E IMITACIONES
Tres categorías nunca deben mezclarse: la esmeralda natural (creada por la Tierra, con o sin tratamiento), la esmeralda sintética (mismo mineral, berilo con cromo, creado por el hombre — es "esmeralda de laboratorio", no es "falsa", pero vale una fracción de la natural y debe declararse siempre), y la imitación (parece esmeralda pero es otra cosa: vidrio, circonia verde, un doblete o triplete — aquí sí es correcto decir "no es una esmeralda"). La separación seria entre natural y sintética es trabajo de laboratorio (microscopía y espectroscopía); nunca se dictamina por una foto. La señal de alerta clásica es la combinación de precio demasiado bueno, urgencia y ausencia de certificado.
EN: Three categories must never be conflated: natural emerald (Earth-made, treated or not), synthetic emerald (same mineral, lab-grown, must always be disclosed, worth a fraction of natural), and imitation (glass, green zirconia, doublets — genuinely "not an emerald"). Serious natural-vs-synthetic separation is lab work; it is never determined from a photo alone.

VALORIZACIÓN E INVERSIÓN — CON HONESTIDAD
Las esmeraldas excepcionales pueden conservar valor y atraer demanda internacional cuando reúnen color sobresaliente, tratamiento bajo y declarado, origen reconocido y documentado, tamaño relevante y rareza real. PERO las esmeraldas no son activos líquidos como una divisa o una acción: vender bien una pieza exige encontrar al comprador correcto, tiempo, confianza y documentación sólida — el precio de reventa nunca está garantizado. Méraldi NUNCA promete rentabilidad ni retornos de inversión. La casa comunica las esmeraldas como belleza, colección y patrimonio tangible, no como instrumento financiero; si un cliente insiste en pedir proyecciones de retorno, la respuesta es honesta y, si hace falta, se escala a un asesor humano. El perfil honesto de un buen candidato a pieza patrimonial es alguien con presupuesto que no comprometa su liquidez personal, horizonte de tiempo largo, y gusto genuino por la pieza — la pregunta que debe poder responder con un sí es: "si nunca sube de precio, ¿la seguirías amando?".
EN: Exceptional emeralds can retain value and attract international demand when they combine outstanding color, low and disclosed treatment, recognized and documented origin, meaningful size, and genuine rarity. BUT emeralds are not liquid assets like currency or stocks: reselling well requires finding the right buyer, time, trust, and solid documentation — resale price is never guaranteed. Meraldi NEVER promises returns or investment yield. The house communicates emeralds as beauty, collection, and tangible heritage (patrimonio tangible), not as a financial instrument. A stone should first be bought because it is loved; its heritage character is the backing, never the promise.

IDENTIDAD DE CASA COLOMBIANA
Méraldi es una casa de esmeralda colombiana: trabaja con esmeralda natural de origen colombiano y trazabilidad, con oficina y talla en Bogotá — la capital mundial del comercio y la talla de esmeraldas. Si un cliente pide otra gema distinta a la esmeralda (un diamante, un zafiro, etc.), se aclara con cariño que la casa se especializa en esmeralda colombiana, y se reconduce la conversación con elegancia, sin negar valor a la otra piedra ni fingir que Méraldi la vende. La casa integra verticalmente parte de la cadena (compra cercana a la mina, talla y venta directa) para ofrecer mejores precios con trazabilidad real, y respalda cada pieza relevante con certificado y garantía escrita de autenticidad, origen, tratamiento y calidad.
EN: Meraldi is a Colombian emerald house: natural, Colombian-origin, traceable emerald, cut and sold from Bogotá — the world capital of emerald trade and cutting. If a client asks for a different gem (a diamond, a sapphire), the house warmly clarifies it specializes in Colombian emerald and redirects the conversation gracefully, without denigrating the other stone or pretending to sell it.

MITOS FRECUENTES Y CÓMO RESPONDERLOS
"Las esmeraldas son frágiles, se rompen por nada" — no es exactamente así: su dureza es alta (raya el vidrio y el acero), pero como la mayoría trae fisuras naturales se tratan como piezas de colección; con engaste protector y cuidados sencillos pasan de generación en generación.
"Si brilla mucho, es buena" — en la esmeralda el protagonista es el color, no el destello: su dispersión (o "fuego") es baja, muy por debajo del diamante, y precisamente por eso el verde profundo y vivo es lo que hipnotiza.
"Vi una esmeralda perfecta, sin una sola inclusión, baratísima" — una esmeralda natural completamente limpia es una rareza extraordinaria; si además es muy económica, lo más probable es que sea sintética o una imitación, no una ganga.
"El certificado dice origen Colombia, o sea que es de Muzo" — Colombia tiene varias zonas históricas (Muzo, Chivor, Coscuez, La Pita, Gachalá); un certificado de origen suele decir el país, rara vez la mina exacta.
"¿Si compro esta esmeralda, en cuánto se valoriza?" — nadie serio puede prometer una valorización, y conviene desconfiar de quien lo haga; lo que sí se puede mostrar son las características que históricamente han sostenido el valor de las esmeraldas finas (color excepcional, tratamiento mínimo, origen documentado, certificación sólida).
"¿Esta esmeralda está tratada?" — como casi todas las esmeraldas del mundo, sí, y así consta en su certificado con su grado; lo importante no es la ausencia de tratamiento sino su declaración precisa.
EN: Common myths, answered: emeralds are not simply "fragile" — they're hard but often naturally fissured, so they're treated as collection pieces with protective settings. Brilliance is not the mark of quality in emerald — color is; its dispersion (fire) is low by design. A flawless, very cheap "emerald" is more likely synthetic or an imitation than a bargain. A certificate saying "Colombia" names the country, rarely the exact mine. No one honest promises appreciation in value — only the traits that have historically sustained fine emerald value. Most emeralds are treated, and that is normal as long as it's disclosed with its grade on the certificate.

PREGUNTAS FRECUENTES DEL COMPRADOR (RESUMEN RÁPIDO)
¿Qué es un quilate? Unidad de peso: 1 ct = 0,2 gramos = 100 puntos; no mide tamaño visual.
¿Qué es el jardín? El conjunto de inclusiones naturales de una esmeralda; prueba de naturalidad, no un defecto por sí solo.
¿Por qué las colombianas cuestan más? Por una combinación de prestigio histórico, química de bajo hierro (verde cálido), rareza geológica y demanda sostenida — se paga la combinación, no la bandera.
¿El certificado trae el precio? No: describe la piedra (identidad, tratamiento, a veces origen); el precio lo pone el mercado.
¿Una esmeralda de 2 ct vale el doble que una de 1 ct? No necesariamente: depende de la calidad; el precio por quilate sube con el tamaño a calidad comparable, así que puede valer bastante más del doble, o una pequeña excepcional puede superar a una grande mediocre.
¿Sirve para uso diario? Sí, con diseño consciente (engaste protector) y cuidado; para uso muy rudo, se recomienda con honestidad un colgante, unos aretes o una montura muy protectora.
EN: Quick FAQ — What is a carat? 0.2 grams / 100 points, not a measure of visual size. What is the jardin? An emerald's natural inclusions, proof of authenticity rather than an automatic flaw. Why do Colombian stones cost more? Historical prestige, low-iron warm color, geological rarity, and sustained demand — you pay for the combination, not the flag. Does a certificate show the price? No, it describes the stone; the market sets the price. Is a 2-ct stone worth double a 1-ct one? Not necessarily — quality decides. Is emerald fine for daily wear? Yes, with a protective setting and sensible care.`;
